services:
  app:
    build: .
    container_name: sourcecode_app
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/sourcecode
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

  db:
    image: postgres:15
    container_name: sourcecode_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
